### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by crvarner** [jshttp/spdy-push#4]
I am attempting to implement http2/spdy push in an express app. I had it working fine with the .push() method exposed by require('spdy'), however this would break in the case of a user aborting a request. When I saw that this module handled connection closing, I thought it might do the trick.

However, setting it up per the documentation I receive the following error:

```
/Users/colevarner/fullpower/node/motionxlive/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/stream.js:662  
return callback(err, push);
       ^
TypeError: callback is not a function
    at /Users/colevarner/fullpower/node/motionxlive/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/stream.js:662:14
    at /Users/colevarner/fullpower/node/motionxlive/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:833:5
    at Object.callback (/Users/colevarner/fullpower/node/motionxlive/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/stream.js:463:5)
    at Framer.tickSync (/Users/colevarner/fullpower/node/motionxlive/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:130:12)
    at Framer.tick (/Users/colevarner/fullpower/node/motionxlive/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:108:13)
    at /Users/colevarner/fullpower/node/motionxlive/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:102:10
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

This seems like some sort of incompatibility with the spdy module.

**Comment by jonathanong** [comment]
yeah this was made for an older version of `spdy`, but i had trouble upgrading. couldn't figure out what changed to make everything break. 

it's not a priority for me now since i can't use this until nginx supports HTTP2 push and so does AWS ELB and Heroku. 

and it might be fruitless if http2 is baked into core.

help welcomed though :)

**Comment by crvarner** [comment]
Just to clarify. I am using the module in the following setup

    var spdy    = require('spdy-push');
    var router  = require('express').Router();

    router.use('/test', function(req,res,next) {
        if (req.isSpdy) {
            spdy(res).push('/js/jquery.min.js',
            {
                headers: headers,
                filename: '../public/js/jquery.min.js'
            }).catch(function (err) {
                console.log(err);
            });
        }
    });
