### ISSUE TITLE
native-or-bluebird is deprecated. please switch to any-promise

### ISSUE THREAD

**Issue by jonathanong** [jshttp/spdy-push#5]
https://github.com/kevinbeaty/any-promise

this implementation supports more promise implementations and allows the end-user to configure the promise implementation.

**Comment by nickserv** [comment]
Could you please publish a patch release so we can fix this [deprecation issue in Koala ](https://github.com/koajs/koala/issues/34)? The published versions still depend on `native-or-bluebird`.
